### ISSUE TITLE
cannot generate project.

### ISSUE THREAD

**Issue by louwangzhiyuY** [microsoft/windows-ai-studio#25]
I waited for an hour,  still stuck in here.  cannot proceed to the next step

![image](https://github.com/microsoft/windows-ai-studio/assets/6920071/6fd4c20b-1a6e-426c-9fa9-ab4d418ad803)

**Comment by ningx-ms** [comment]
Hi @louwangzhiyuY 

It will take a while when creating a project for the first time as it will download many dependent packages to create the conda environment, in additional to the model files.

For example, it took me ~10min to create a Mistral-7b project in a clean setup, with high-speed internet. 

```
Debug: generate-project[0]
   12:28:53.02 0 RunProcess data:Script execution completed.
Debug: generate-project[0]
   12:28:53.03 0 RunProcess exit code:0 elapsed:00:07:20.8384747
Debug: generate-project[0]
   12:28:53.03 0 ExecuteAsync Completed Elapsed:00:09:40.4726657
[2024-01-03T20:28:53.046Z] [INFO] Command executed to generate the project
[2024-01-03T20:30:29.719Z] [INFO] Command executed to generate the project
```

Have you tried to recreate the project with reliable internet connection?
