### ISSUE TITLE
Hangs at "Validating requirements..."

### ISSUE THREAD

**Issue by natewaddoups** [microsoft/windows-ai-studio#26]
I installed the extension and clicked the sidebar button, and the AI Studio pane says "validating requirements..." with a corresponding notification in the lower left, and was in that state for about three hours. The results haven't appeared anywhere. When I ran this on another PC, the results came up after just a minute or so.

I retried a couple times with the same results.

(Nitpicking: the notification has a typo: "environement" with an extra "e" in the midle.)

Details from the machine where it hung:

VS:

Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Output window:

[2023-12-15T22:45:37.928Z] [INFO] Command registration.
[2023-12-15T22:45:37.931Z] [INFO] Validating environment on activation.
[2023-12-15T22:45:37.931Z] [INFO] Extenension: Invoking validateEnvironement for: All
Debug: validate-env[0]
   02:45:38.16 0 ExecuteAsync Started
Information: validate-env[0]
   02:45:38.89 0 IsWSLDetected Execution
[2023-12-15T22:45:40.161Z] [INFO] telemetry event:activate_extension sent

System info:

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Puget Systems
System Model	MS-7C76
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2.30, 10/12/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	MPG Z490M GAMING EDGE WIFI (MS-7C76)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume4
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
Time Zone	Pacific Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	16.8 GB
Total Virtual Memory	45.4 GB
Available Virtual Memory	20.3 GB
Page File Space	13.5 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

GPUs:

Name	Intel(R) UHD Graphics 630
PNP Device ID	PCI\VEN_8086&DEV_9BC5&SUBSYS_7C761462&REV_05\3&11583659&0&10
Adapter Type	Intel(R) UHD Graphics Family, Intel Corporation compatible
Adapter Description	Intel(R) UHD Graphics 630
Adapter RAM	1.00 GB (1,073,741,824 bytes)
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd12umd64.dll
Driver Version	31.0.101.2111
INF File	oem147.inf (iCML_w10_DS section)
Color Planes	Not Available
Color Table Entries	Not Available
Resolution	Not Available
Bits/Pixel	Not Available
Memory Address	0xCF000000-0xCFFFFFFF
Memory Address	0xD0000000-0xDFFFFFFF
I/O Port	0x0000FFC0-0x0000FFFF
IRQ Channel	IRQ 4294967257
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\IIGD_DCH.INF_AMD64_51F685305808E3A5\IGDKMD64.SYS (31.0.101.2111, 42.18 MB (44,233,280 bytes), 10/13/2022 4:11 AM)
	
Name	NVIDIA GeForce RTX 3080
PNP Device ID	PCI\VEN_10DE&DEV_2206&SUBSYS_146710DE&REV_A1\4&20C8D46&0&0008
Adapter Type	NVIDIA GeForce RTX 3080, NVIDIA compatible
Adapter Description	NVIDIA GeForce RTX 3080
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvldumdx.dll
Driver Version	31.0.15.3623
INF File	oem47.inf (Section070 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	3840 x 2160 x 59 hertz
Bits/Pixel	32
Memory Address	0xC3000000-0xC40FFFFF
Memory Address	0xB0000000-0xC1FFFFFF
Memory Address	0xC0000000-0xC1FFFFFF
I/O Port	0x00004000-0x00004FFF
IRQ Channel	IRQ 4294967222
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\NV_DISPIG.INF_AMD64_7E5FD280EFAA5445\NVLDDMKM.SYS (31.0.15.3623, 56.27 MB (59,007,984 bytes), 8/15/2023 4:55 AM)

**Comment by BenjaminFourmaux** [comment]
Same issue for me.

After add Ubuntu distro as default, the Visual Studio plugin not show the startup page. Stuck at "Validating requirements...".
And in the console :
```shell
[2023-12-18T16:01:39.985Z] [INFO] Command registration.
[2023-12-18T16:01:39.985Z] [INFO] Validating environment on activation.
[2023-12-18T16:01:39.985Z] [INFO] Extenension: Invoking validateEnvironement for: All
Debug: validate-env[0]
   05:01:40.03 0 ExecuteAsync Started
Information: validate-env[0]
   05:01:40.14 0 IsWSLDetected Execution
[2023-12-18T16:01:42.906Z] [INFO] telemetry event:activate_extension sent
```

I have tried to change the `nameserver` to `8.8.8.8` in the `/etc/resolv.conf` file in wsl, but nothing.

OS :
Windows 10 Entreprise
Version : 22h2

GPU :
NVIDIA GeForce RTX 3050 Ti Laptop GPU
Driver version : 528.79

WSL :
Version 2
Distri : Ubuntu 22.4.3 LTS

**Comment by acube3** [comment]
Please update your NVidia driver to the latest version and try the following command in WSL and share the results of the same:
nvidia-smi

Also, please share the log files saved in the following folder after retrying the workspace creation again? (alternatively, you can only share log files for the date when )
%USERPROFILE%\.wais
You can use Windows+R to open the above folder location.

**Comment by BenjaminFourmaux** [comment]
Resolved for me !

I just update wsl and re-install Ubuntu
```powershell
wsl --update
```
> Don't forget to set Ubuntu as default wsl distro
