### ISSUE TITLE
Not worked, no source code

### ISSUE THREAD

**Issue by Serg2DFX** [microsoft/windows-ai-studio#38]
Hello.

Extension not worked with the pre-installed conda.

Does not see GPU and WSL.

![2024-01-06 124928](https://github.com/microsoft/windows-ai-studio/assets/5922647/a8aa3f73-6d3f-4c31-9de5-22766ddf9ae3)
![2024-01-06 124951](https://github.com/microsoft/windows-ai-studio/assets/5922647/f1f73aa8-f9a6-43fa-bca3-b7edb0024c19)
![2024-01-06 125330](https://github.com/microsoft/windows-ai-studio/assets/5922647/3a117dca-63e5-46af-9715-00aa18e05471)

VALIDATE MACHINE ENVIRONMENT
Uh oh...

Setup WSL Environment
We found some missing requirements for your environment. Check the sections below to resolve the issues.
Prerequisites
Issues here you will need to fix yourself.
NVIDIA GPU detected.
WSL detected.
WSL Ubuntu distro 18.4 or greater detected.
WSL Ubuntu distro 18.4 or greater detected AND is the default.
To install Windows subsytem for Linux learn more [here](https://learn.microsoft.com/en-us/windows/wsl/install).

Learn more about changing default distribution [here](https://learn.microsoft.com/en-us/windows/wsl/install#change-the-default-linux-distribution-installed).

WSL Environment
Good news! Issues here should be fixed by clicking the 'Setup WSL Environment' button above.
Conda detected.
CUDA Libraries detected.

**Comment by Serg2DFX** [comment]
Full output:

[2024-01-06T09:54:17.884Z] [INFO] Command registration.
[2024-01-06T09:54:17.885Z] [INFO] Validating environment on activation.
[2024-01-06T09:54:17.885Z] [INFO] Extenension: Invoking validateEnvironement for: All
Debug: validate-env[0]
   12:54:17.93 0 ExecuteAsync Started
Information: validate-env[0]
   12:54:18.06 0 IsWSLDetected Execution
Error: validate-env[0]
   12:54:18.21 0 The default WSL distribution is not Ubuntu. Please set Ubuntu 18.04 or greater as the default.
Debug: validate-env[0]
   12:54:18.21 0 ExecuteAsync Completed Elapsed:00:00:00.2883496
[2024-01-06T09:54:18.217Z] [INFO] Validation outcome prereqsmet: false
[2024-01-06T09:54:18.217Z] [INFO] Initialize WebView pane.
[2024-01-06T09:54:18.218Z] [INFO] Navigating view to requirements page.
[2024-01-06T09:54:18.394Z] [INFO] Navigation to loadPrerequisiteCheck was successful: true
[2024-01-06T09:54:18.395Z] [INFO] Loading View: loadPrerequisiteCheck
[2024-01-06T09:54:18.400Z] [INFO] Extenension: Invoking validateEnvironement for: conda
Debug: validate-env[0]
   12:54:18.43 0 ExecuteAsync Started
Information: validate-env[0]
   12:54:18.50 0 IsCondaInstalled Execution
Information: validate-env[0]
   12:54:18.68 0 IsCondaInstalled : False
Debug: validate-env[0]
   12:54:18.68 0 ExecuteAsync Completed Elapsed:00:00:00.2499132
[2024-01-06T09:54:18.685Z] [INFO] Extenension: Invoking validateEnvironement for: cuda-runtime
Debug: validate-env[0]
   12:54:18.71 0 ExecuteAsync Started
Information: validate-env[0]
   12:54:18.78 0 IsCudaRuntimeInstalled Execution
Error: validate-env[0]
   12:54:18.88 0 Error: /bin/ash: bash: not found

Information: validate-env[0]
   12:54:18.88 0 IsCudaRuntimeInstalled : False
Debug: validate-env[0]
   12:54:18.88 0 ExecuteAsync Completed Elapsed:00:00:00.1721669
[2024-01-06T09:54:18.889Z] [INFO] Extenension: Invoking validateEnvironement for: nvidia-driver
Debug: validate-env[0]
   12:54:18.91 0 ExecuteAsync Started
Information: validate-env[0]
   12:54:18.98 0 IsNvidiaDiverAvailable Execution
Error: validate-env[0]
   12:54:19.09 0 Error: /bin/ash: nvidia-smi: not found

Information: validate-env[0]
   12:54:19.09 0 IsNvidiaDiverAvailable : False
Debug: validate-env[0]
   12:54:19.09 0 ExecuteAsync Completed Elapsed:00:00:00.1768474
[2024-01-06T09:54:19.097Z] [INFO] Extenension: Invoking validateEnvironement for: wsl-detected
Debug: validate-env[0]
   12:54:19.12 0 ExecuteAsync Started
Information: validate-env[0]
   12:54:19.20 0 IsWSLDetected Execution
Debug: validate-env[0]
   12:54:19.26 0 ExecuteAsync Completed Elapsed:00:00:00.1400184
[2024-01-06T09:54:19.267Z] [INFO] Extenension: Invoking validateEnvironement for: wsl-distro-ubuntu1804OrGreater
Debug: validate-env[0]
   12:54:19.29 0 ExecuteAsync Started
Error: validate-env[0]
   12:54:19.53 0 Error: /bin/ash: lsb_release: not found

Error: validate-env[0]
   12:54:19.63 0 Error: /bin/ash: lsb_release: not found

Error: validate-env[0]
   12:54:19.73 0 Error: /bin/ash: lsb_release: not found

Debug: validate-env[0]
   12:54:19.73 0 ExecuteAsync Completed Elapsed:00:00:00.4395848
[2024-01-06T09:54:19.785Z] [INFO] Extenension: Invoking validateEnvironement for: wsl-distro-ubuntu1804OrGreater-default
Debug: validate-env[0]
   12:54:19.81 0 ExecuteAsync Started
Error: validate-env[0]
   12:54:19.94 0 The default WSL distribution is not Ubuntu. Please set Ubuntu 18.04 or greater as the default.
Debug: validate-env[0]
   12:54:19.94 0 ExecuteAsync Completed Elapsed:00:00:00.1356121
[2024-01-06T09:54:20.713Z] [INFO] telemetry event:activate_extension sent
[2024-01-06T09:54:20.713Z] [INFO] telemetry event:requirements_needed sent

**Comment by acube3** [comment]
Here is the problem that your debug output is reporting:
The default WSL distribution is not Ubuntu. Please set Ubuntu 18.04 or greater as the default.
Please set the default distro Ubuntu-22.04 using the following command and retry.
wsl --set-default Ubuntu-22.04
Also run:
wsl --update
Also, please make sure that your NVidia driver is updated.

**Comment by Serg2DFX** [comment]
it's strange way to solve problems)

![image](https://github.com/microsoft/windows-ai-studio/assets/5922647/92d6f6e3-0fa2-4e91-b60a-4762cce7f28f)

Next, conda not detected.
But,

![image](https://github.com/microsoft/windows-ai-studio/assets/5922647/86292b99-021d-4570-98d2-e78e6e302d4c)

**Comment by ningx-ms** [comment]
Hi @Serg2DFX this bug will be fixed in next release, will post here once the update is out.

**Comment by ningx-ms** [comment]
@Serg2DFX  we just released `0.2.2 preview`, please give it a try and let us know if the Conda installation issue has been resolved. Thx.

**Comment by Serg2DFX** [comment]
It didn't help.
![image](https://github.com/microsoft/windows-ai-studio/assets/5922647/1a591e13-83aa-40e4-850c-fff3b84ba62b)

do I need to collect additional logs?

[conda-info.txt](https://github.com/microsoft/windows-ai-studio/files/13906976/conda-info.txt)
[logs.txt](https://github.com/microsoft/windows-ai-studio/files/13906977/logs.txt)

**Comment by Serg2DFX** [comment]
I install sudo apt-get install lsb-core
but not worked
![image](https://github.com/microsoft/windows-ai-studio/assets/5922647/8e942965-c39f-4555-b557-312a5a4425ea)
[logs_2.txt](https://github.com/microsoft/windows-ai-studio/files/13907034/logs_2.txt)

**Comment by ningx-ms** [comment]
Thanks for the test and logs.

Could you share the most recent `*.cli.log` in `%USERPROFILE%\.wais` on Windows, for example `20240104-260872-cli.log`?

This is the log file created by this extension which logs the environment setup events.

**Comment by Serg2DFX** [comment]
I'm not sure they'll help
[20240111-18132-logs.zip](https://github.com/microsoft/windows-ai-studio/files/13907149/20240111-18132-logs.zip)

**Comment by ningx-ms** [comment]
Please click `Setup WSL Environment` button on the top right to allow the extension to install Conda env and some dependent packages.
Once done, the extension will check the conda again and update the GUI. 

If Conda still cannot be detected, please update the CLI logs for `Setup WSL Environment` operation.

**Comment by Serg2DFX** [comment]
Thank you, pressing the button helped.

**Comment by Serg2DFX** [comment]
Thank you, pressing the button helped.
