### ISSUE TITLE
how can i convert my finetunned model to GGUF.

### ISSUE THREAD

**Issue by jeewanjoga** [microsoft/windows-ai-studio#45]
i have successfully funetunned phi-2 model with windows AI Studio, and it works fine, i want use model with llamaccp, how can i convert this model to GGUF,

**Comment by ningx-ms** [comment]
Ai Studio doesn't support model conversion to GGUF right now.

You can find many posts on the conversions, like below.
https://www.substratus.ai/blog/converting-hf-model-gguf-model/

And someone has already converted Phi-2 to gguf.
https://huggingface.co/TheBloke/phi-2-GGUF
